### ISSUE TITLE
local variable 'cpucount' referenced before assignment

### ISSUE THREAD

**Issue by bedroge** [rug-cit-ris/slurm-jobinfo#16]
I just got this error when trying to retrieve some job information:

```
$ jobinfo 18732555
Job ID              : 18732555
Name                : runFPN2_dogs_Train_5way5shot_Nshot_kernel3.sh
User                : p266364
Partition           : lab
Nodes               : pg-lab01
Number of Nodes     : 1
Cores               : 1
State               : CANCELLED,TIMEOUT
Submit              : 2021-03-20T20:34:12
Start               : 2021-03-20T20:34:12
End                 : 2021-03-21T20:34:30
Reserved walltime   : 1-00:00:00
Used walltime       : 1-00:00:18
Used CPU time       :   23:59:01 (efficiency: 99.91%)
% User (Computation): 73.24%
% System (I/O)      : 26.76%
Mem reserved        : 120G/node
Max Mem used        : 2.69G (pg-lab01)
Max Disk Write      : 122.88K (pg-lab01)
Max Disk Read       : 2.63M (pg-lab01)
Traceback (most recent call last):
  File "/usr/bin/jobinfo", line 518, in <module>
    main(jobid)
  File "/usr/bin/jobinfo", line 488, in main
    get_hints(meta)
  File "/usr/bin/jobinfo", line 251, in get_hints
    cores_max_node = get_cpus_node(meta.MaxRSSNode)
  File "/usr/bin/jobinfo", line 207, in get_cpus_node
    return cpucount
UnboundLocalError: local variable 'cpucount' referenced before assignment
```

**Comment by bedroge** [comment]
This only happens when you are not in the group that allows you to use the lab partition, but do want to run jobinfo on jobs from that partition.
